SIM ?= verilator
TOPLEVEL_LANG ?= verilog
WAVES=1
VERILOG_SOURCES += $(PWD)/half_adder.sv
COCOTB_TOPLEVEL = half_adder
COCOTB_TEST_MODULES = MyTest
include $(shell cocotb-config --makefiles)/Makefile.sim