SIM ?= verilator
TOPLEVEL_LANG ?= verilog
WAVES=1
VERILOG_SOURCES += $(PWD)/adder_4bits.sv
COCOTB_TOPLEVEL = adder_4bits
COCOTB_TEST_MODULES = MyTest
include $(shell cocotb-config --makefiles)/Makefile.sim