SIM ?= verilator
TOPLEVEL_LANG ?= verilog
WAVES=1
VERILOG_SOURCES += $(PWD)/moore_fsm.sv
COCOTB_TOPLEVEL = moore_fsm
COCOTB_TEST_MODULES = MyTest
GUI = 1
include $(shell cocotb-config --makefiles)/Makefile.sim