VERILOG_SOURCES += half_adder.v
VERILOG_SOURCES += full_adder.v
VERILOG_SOURCES += adder_4bits.v

COCOTB_TEST_MODULES = uvm_adder_4bits

TOPLEVEL = adder_4bits

include $(shell cocotb-config --makefiles)/Makefile.sim